android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
kotlin.daemon.jvmargs=-Xmx2g
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.disallowKotlinSourceSets=false
# Disabling these to rule out build-system interference with the emulator
android.newDsl=false
org.gradle.configuration-cache=false
